name: Trigger auto deployment for productapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/productapi-AutoDeployTrigger-beb26720-dc0e-4a6d-a54c-d687d09e728d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PRODUCTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRODUCTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRODUCTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: utcshop.azurecr.io
          registryUsername: ${{ secrets.PRODUCTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRODUCTAPI_REGISTRY_PASSWORD }}
          containerAppName: productapi
          resourceGroup: UTCShopAPIContainerApps
          imageToBuild: utcshop.azurecr.io/productapi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


